version: '3.8'

services:
  mysql:
    image: pokemon-mysql
    build:
      context: .
      dockerfile: ./Dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: pokemon
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 3306:3306
    networks:
      - pokemon-network

  rest:
    depends_on:
      - mysql
    container_name: pokemon-app
    image: pokemon-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - pokemon-network

  #react:
  #  depends_on:
  #    - rest
  #  container_name: pokemon_react
  #  image: pokemon_react
  #  build:
  #    context: ../pokedexReact
  #    dockerfile: Dockerfile.react
  #  ports:
  #    - 3006:3006
  #  networks:
  #   - pokemon-network

networks:
  pokemon-network:
    driver: bridge
